language: ruby
cache: bundler
rvm:
- 2.1.1
env:
- DB=sqlite
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- RAILS_ENV=test
- bundle exec rake db:migrate
- bundle exec rake --trace spec
addons:
  code_climate:
    repo_token: e9a6dd5ab425b356ac7bc438c5ef47986996de74799f70527bd69d48c2b053f0
notifications:
  email: false
  slack:
    rooms:
    - gangoffourorfive:M8oPDrLhcUb55JaKrZIijmI5#general
deploy:
  provider: heroku
  api_key:
    secure: jl7m94tiJxJW8DfOXpato/yhp3kAgAlg7ySBnNe3xm+wIu2G5u6cGKssASFiqRMtpN3UAUf8/RSNUOCtAmS7LaP4347hfpHwgqNwEObiVgMrpYQDy+3ynbkRQmLo3CbhuyAnr65Q0NWq+qiaDQMMAqibZCPxzjX9k/lBBRcTrdI=
  app: reservira
