language: ruby
cache: bundler
rvm:
  - 2.1.1
env:
  - DB=sqlite
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
- RAILS_ENV=test
- bundle exec rake db:migrate
- bundle exec rake --trace spec
deploy:
  provider: heroku
  api_key:
    secure: nzOVeQvj0VqMDfVw8JV5vLWCQ9E/ZzFmrKzJZT4oDIz9R6MQUn1bIgUFNgHGUqThVo8TwayJoHHQqUFRTX6gTtdtzmjxEhrhqZob2L3elHuIGR+xayRiFhrsYFvOQUxiioerVopv5SeYevSk4Sf8sCnRGQzomuM9JLT477yLN4g=
  app: reservira
  on:
    repo: GanfOfFourOrFive/reservira
notifications:
  email: false    
