# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fa8e2cf519053f90252a71fc3eecfc08fff40a157fca2e0808e88eaeed9d2762a5689b3084cee1915669f79846c530388f4e905e57906676f3cd401d88448d5

test:
  secret_key_base: 7cb5ffcadc23694b517f65a10ab25eeeca8d79c002f2e4d65b7bdb43df9aed46a2613115d6b918cdeba3debfa1b431ca7f19df2490c5f0b0e0b107d604086869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
